#!/bin/bash

while getopts ":d:" input;do
        case "$input" in
                d) domain=${OPTARG}
                        ;;
                esac
        done
if [ -z "$domain" ]
        then
                echo "Please give a domain like \"-d domain.com\""
                exit 1
fi
echo 
echo -e "#########################################################      Hello Dr     ######################################################\n"
echo -e "#########################################################Starting sublist3r ######################################################\n"
sublist3r -d $domain -b -o sublister.txt

echo 
echo -e "#########################################################Starting subfinder ######################################################\n"
subfinder -d $domain -o subfinder.txt

echo 
echo -e "########################################################Starting assetfinder ######################################################\n"
assetfinder --subs-only $domain | tee -a assetfinder.txt

echo 
echo -e "###################################################Starting github subdomains enumeration ##########################################\n"
python3 ~/tools/github-subdomains.py -t ###yours###-d $domain | tee -a github.txt

echo 
echo -e "########################################################Starting amass passive ####################################################\n"
amass enum -passive -d "$domain" | tee -a amasspassive.txt


cat sublister.txt subfinder.txt assetfinder.txt github.txt amasspassive.txt > passive1.txt
rm sublister.txt subfinder.txt assetfinder.txt github.txt amasspassive.txt
cat passive1.txt | sort -u > passive.txt

echo
echo -e "##########################################################Starting amass active ###################################################\n"
amass enum -active -d $domain -ip | tee -a amass_ips.txt
cat amass_ips.txt | awk '{print $1}' | tee -a passive.txt
cat passive.txt | sort -u | tee -a all.txt

echo 
echo -e "####################################################Starting Bruteforce##############################################################\n"
altdns -i all.txt -o data_output -w ~/tools/recon/words.txt -r -s dns_op.txt
cat dns_op.txt |sort -u | cut -d ":" -f 2 | sed 's/\.$//' | tee -a all.txt

echo 
echo -e "###############################################Checking for alive subdomains#########################################################\n"
cat all.txt | httprobe --prefer-https | tee -a alive2.txt
cat alive2.txt | sort -u | tee -a alive.txt
rm alive2.txt passive.txt amass_ips.txt dns_op.txt data_output passive1.txt

echo 
echo -e "############################################ enumerating working subdomains for manual testing ############################################\n"
cat all.txt | httpx -fc 404 -o working-subdomains.txt

echo 
echo -e " ##########################################looking for subdomain takeover ############################################################\n"
python3 /root/tools/subdomain-takeover/takeover.py -d $domain -f all.txt -t 3 | tee -a subdomain-takeover.txt

echo 
echo -e "####################################################Starting nmap################################################################\n"
cat alive.txt | cut -d "/" -f 3 > fornmap.txt
nmap -iL fornmap.txt --top-ports 2000 --exclude-ports 80,443,8080 -sV -sC > nmap-report.txt
cat nmap-report.txt | grep -w 'ftp\|ssh\|mysql\|rbcbind\|smtp\|snmp' | tee -a nmap-interesting.txt

echo 
echo -e "############################################Looking for Public s3 Buckets ##########################################################\n"
s3scanner --threads 1 scan --buckets-file fornmap.txt > s3-report.txt
cat s3-report.txt | grep bucket_exists > found-s3buckets.txt 
echo 
echo -e "###################################################### trying to bypass 403 #####################################################\n"
mkdir 403
cd 403
while read LINE; do curl -o /dev/null --silent --head --write-out "%{http_code} $LINE\n" "$LINE"; done < ../alive.txt | awk '/403/ || /denied/' {print $2}'| tee -a 403.txt
python3 ~/tools/403bypasser/403bypasser.py -U 403.txt -d admin | awk '/404/ || /200/' | tee -a ../403bybassed.txt
cd ..

echo 
echo -e "####################################################Starting Nuclei#################################################\n"
mkdir nuclei_op
nuclei -l working-subdomains.txt -t "/root/tools/nuclei-templates/cves/*.yaml" -c 60 -o nuclei_op/cves.txt
nuclei -l working-subdomains.txt -t "/root/tools/nuclei-templates/file/*.yaml" -c 60 -o nuclei_op/files.txt
nuclei -l working-subdomains.txt -t "/root/tools/nuclei-templates/exposed-panels/*.yaml" -c 60 -o nuclei_op/panels.txt
nuclei -l working-subdomains.txt -t "/root/tools/nuclei-templates/misconfiguration/*.yaml" -c 60 -o nuclei_op/security-misconfiguration.txt
nuclei -l working-subdomains.txt -t "/root/tools/nuclei-templates/technologies/*.yaml" -c 60 -o nuclei_op/technologies.txt
nuclei -l working-subdomains.txt -t "/root/tools/nuclei-templates/token-spray/*.yaml" -c 60 -o nuclei_op/tokens.txt
nuclei -l working-subdomains.txt -t "/root/tools/nuclei-templates/vulnerabilities/*.yaml" -c 60 -o nuclei_op/vulnerabilities.txt




echo 
echo -e "##############################################Now looking for CORS misconfiguration##############################################\n"
python3 ~/tools/Corsy/corsy.py -i working-subdomains.txt -t 40 | tee -a corsy_op.txt




echo 
echo -e "##############################################looking for public .git Folder ##############################################\n"
meg -s 200 /root/tools/paths.txt ./alive.txt
cd out
cat index | cut -d " " -f 2 > ../git.txt
cd ..
rm -r out

#echo 
#echo "########################################################Starting dirsearch########################################################\n"
#cp working-subdomains.txt ~/
#python3 /root/tools/dirsearch/dirsearch.py -i 200 -l ~/working-subdomains.txt --max-time=120 -o dirsearch.txt
#rm ~/working-subdomains.txt
# -e php,bak,zip,tar,git,sh,py,txt,sql,aspx,jsp,html,js 


echo 
echo "########################################################Starting dirsearch########################################################\n"
rm -r /root/.dirsearch/reports/ 
for i in $(cat alive.txt);do dirsearch -u $i -i 200 --max-time=500 ;done 
find /root/.dirsearch/reports/ -type f -print0 | xargs -0 cat *.txt | grep ^200 | tee -a dirsearch.txt
rm -r /root/.dirsearch/reports/ 




echo 
echo -e "#################################################Starting wayback data gathering################################################\n"
mkdir wayback_data
cd wayback_data
for i in $(cat ../all.txt);do echo $i | waybackurls ;done | tee -a wb1.txt | sort -u > wb.txt
cat wb.txt  | sort -u | unfurl --unique keys | tee -a paramlist.txt

cat wb.txt u | grep -P "\w+\.js(\?|$)" | sort -u | tee -a jsurls.txt

cat wb.txt  | grep -P "\w+\.php(\?|$)" | sort -u  | tee -a phpurls.txt

cat wb.txt  | grep -P "\w+\.aspx(\?|$)" | sort -u  | tee -a aspxurls.txt

cat wb.txt  | grep -P "\w+\.jsp(\?|$)" | sort -u | tee -a jspurls.txt

cat wb.txt  | grep -P "\w+\.txt(\?|$)" | sort -u  | tee -a robots.txt

rm wb1.txt

cd ..

echo 
echo -e "#################################################Looking for HTTP request smugglig##########################################\n"
python3 ~/tools/http-request-smuggling/smuggle.py -urls alive.txt > smuggle-report.txt
cat smuggle-report.txt | grep Possible > smuggle-found.txt


mkdir scripts
mkdir scriptsresponse
mkdir endpoints
mkdir responsebody
mkdir headers

jsep()
{
response(){
echo -e "########################################################Gathering Response#################################################\n"
        for x in $(cat alive.txt)
do
        NAME=$(echo $x | awk -F/ '{print $3}')
        curl -X GET -H "X-Forwarded-For: evil.com" $x -I > "headers/$NAME"
        curl -s -X GET -H "X-Forwarded-For: evil.com" -L $x > "responsebody/$NAME"
done
}

jsfinder(){
echo -e "#################################################Gathering JS Files########################################################\n"
for x in $(ls "responsebody")
do
        printf "\n\n${RED}$x${NC}\n\n"
        END_POINTS=$(cat "responsebody/$x" | grep -Eoi "src=\"[^>]+></script>" | cut -d '"' -f 2)
        for end_point in $END_POINTS
        do
                len=$(echo $end_point | grep "http" | wc -c)
                mkdir "scriptsresponse/$x/" > /dev/null 2>&1
                URL=$end_point
                if [ $len == 0 ]
                then
                        URL="https://$x$end_point"
                fi
                file=$(basename $end_point)
                curl -X GET $URL -L > "scriptsresponse/$x/$file"
                echo $URL >> "scripts/$x"
        done
done
}

endpoints()
{
echo -e "###############################################################Gathering Endpoints#################################################\n"
for domain in $(ls scriptsresponse)
do
        #looping through files in each domain
        mkdir endpoints/$domain
        for file in $(ls scriptsresponse/$domain)
        do
                ruby ~/tools/relative-url-extractor/extract.rb scriptsresponse/$domain/$file >> endpoints/$domain/$file
        done
done

}
response
jsfinder
endpoints
}
jsep

cat endpoints/*/* | sort -u | tee -a endpoints.txt


echo "###############################################################    end    ################################################################"
