#!/bin/bash

while getopts ":d:" input;do
        case "$input" in
                d) domain=${OPTARG}
                        ;;
                esac
        done
if [ -z "$domain" ]
        then
                echo "Please give a domain like \"-d domain.com\""
                exit 1
fi



echo -e "######Starting sublist3r ######\n"
sublist3r -d $domain -o sublister.txt

echo -e "######Starting subfinder ######\n"
subfinder -d $domain -o subfinder.txt

echo -e "######Starting assetfinder ######\n"
assetfinder --subs-only $domain > assetfinder.txt

echo -e "######Starting github subdomains enumeration ######\n"
python3 ~/tools/github-subdomains.py -t token -d $domain > github.txt

cat sublister.txt subfinder.txt assetfinder.txt github.txt > passive1.txt
rm sublister.txt subfinder.txt assetfinder.txt github.txt

echo -e "######Starting amass passive ######\n"
amass enum -passive -d $doamin | tee -a passive1.txt
cat passive1.txt | sort -u > passive.txt
echo
echo "###########Checking for alive subdomains################"
cat passive.txt | httprobe | tee -a alive2.txt
cat alive2.txt | sort -u | tee -a alive-passive.txt
rm alive2.txt passive1.txt
echo


echo -e "######Starting amass active ######\n"
amass enum -active -d $domain -ip | tee -a amass_ips.txt
cat amass_ips.txt | awk '{print $1}' | tee -a passive.txt
cat passive.txt | sort -u | tee -a all.txt

echo -e "######Starting Bruteforce######\n"
altdns -i all.txt -o data_output -w ~/tools/recon/words.txt -r -s dns_op.txt
cat dns_op.txt | sort -u | tee -a all.txt

echo "###########Checking for alive subdomains################"
cat all.txt | httprobe | tee -a alive2.txt
cat alive2.txt | sort -u | tee -a alive.txt
rm alive2.txt passive.txt alive-passive.txt amass_ips.txt dns_op.txt



echo -e "######looking for subdomain takeover ######\n"

python3 /root/subdomain-takeover/takeover.py -d $domain -f all.txt -t 3 > subdomain-takeover.txt






echo "Starting Nuclei"
mkdir nuclei_op
nuclei -l alive.txt -t "/root/tools/nuclei-templates/cves/*.yaml" -c 60 -o nuclei_op/cves.txt
nuclei -l alive.txt -t "/root/tools/nuclei-templates/file/*.yaml" -c 60 -o nuclei_op/files.txt
nuclei -l alive.txt -t "/root/tools/nuclei-templates/exposed-panels/*.yaml" -c 60 -o nuclei_op/panels.txt
nuclei -l alive.txt -t "/root/tools/nuclei-templates/misconfiguration/*.yaml" -c 60 -o nuclei_op/security-misconfiguration.txt
nuclei -l alive.txt -t "/root/tools/nuclei-templates/technologies/*.yaml" -c 60 -o nuclei_op/technologies.txt
nuclei -l alive.txt -t "/root/tools/nuclei-templates/token-spray/*.yaml" -c 60 -o nuclei_op/tokens.txt
nuclei -l alive.txt -t "/root/tools/nuclei-templates/vulnerabilities/*.yaml" -c 60 -o nuclei_op/vulnerabilities.txt




echo "Now looking for CORS misconfiguration"
python3 ~/tools/Corsy/corsy.py -i alive.txt -t 40 | tee -a corsy_op.txt

echo "Starting CMS detection"
whatweb -i alive.txt | tee -a whatweb_op.txt


mkdir wayback_data
cd wayback_data
for i in $(cat ../all.txt);do echo $i | waybackurls ;done | tee -a wb.txt
cat wb.txt  | sort -u | unfurl --unique keys | tee -a paramlist.txt

cat wb.txt u | grep -P "\w+\.js(\?|$)" | sort -u | tee -a jsurls.txt

cat wb.txt  | grep -P "\w+\.php(\?|$)" | sort -u  | tee -a phpurls.txt

cat wb.txt  | grep -P "\w+\.aspx(\?|$)" | sort -u  | tee -a aspxurls.txt

cat wb.txt  | grep -P "\w+\.jsp(\?|$)" | sort -u | tee -a jspurls.txt

cat wb.txt  | grep -P "\w+\.txt(\?|$)" | sort -u  | tee -a robots.txt

rm wb.txt
cd ..

echo "Looking for HTTP request smugglig"
python3 ~/tools/smuggler.py -u alive.txt | tee -a smuggler_op.txt

mkdir scripts
mkdir scriptsresponse
mkdir endpoints
mkdir responsebody
mkdir headers

jsep()
{
response(){
echo "Gathering Response"       
        for x in $(cat alive.txt)
do
        NAME=$(echo $x | awk -F/ '{print $3}')
        curl -X GET -H "X-Forwarded-For: evil.com" $x -I > "headers/$NAME" 
        curl -s -X GET -H "X-Forwarded-For: evil.com" -L $x > "responsebody/$NAME"
done
}

jsfinder(){
echo "Gathering JS Files"       
for x in $(ls "responsebody")
do
        printf "\n\n${RED}$x${NC}\n\n"
        END_POINTS=$(cat "responsebody/$x" | grep -Eoi "src=\"[^>]+></script>" | cut -d '"' -f 2)
        for end_point in $END_POINTS
        do
                len=$(echo $end_point | grep "http" | wc -c)
                mkdir "scriptsresponse/$x/" > /dev/null 2>&1
                URL=$end_point
                if [ $len == 0 ]
                then
                        URL="https://$x$end_point"
                fi
                file=$(basename $end_point)
                curl -X GET $URL -L > "scriptsresponse/$x/$file"
                echo $URL >> "scripts/$x"
        done
done
}

endpoints()
{
echo "Gathering Endpoints"
for domain in $(ls scriptsresponse)
do
        #looping through files in each domain
        mkdir endpoints/$domain
        for file in $(ls scriptsresponse/$domain)
        do
                ruby ~/tools/relative-url-extractor/extract.rb scriptsresponse/$domain/$file >> endpoints/$domain/$file 
        done
done

}
response
jsfinder
endpoints
}
jsep

cat endpoints/*/* | sort -u | tee -a endpoints.txt

for i in $(cat alive.txt);do ffuf -u $i/FUZZ -w ~/tools/dirsearch/db/dicc.txt -mc 200 -t 60 ;done| tee -a ffuf_op.txt

